export const toolDefinitions: Record<string, any> = {
  "jpg-to-png": {
    label: "JPG → PNG",
    description: "Convert JPEG images to PNG format.",
    actionLabel: "Convert JPG to PNG",
    apiEndpoint: "/image/jpg-to-png",
    acceptedFormats: ".jpg,.jpeg",
    category: "Image Conversion",
    supportsQuality: false,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: false,
  },
  "png-to-jpg": {
    label: "PNG → JPG",
    description: "Convert PNG images to JPEG format.",
    actionLabel: "Convert PNG to JPG",
    apiEndpoint: "/image/png-to-jpg",
    acceptedFormats: ".png",
    category: "Image Conversion",
    supportsQuality: true,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: false,
    defaultQuality: 85,
  },
  "webp-to-jpg": {
    label: "WebP → JPG",
    description: "Convert WebP images to JPEG format.",
    actionLabel: "Convert WebP to JPG",
    apiEndpoint: "/image/webp-to-jpg",
    acceptedFormats: ".webp",
    category: "Image Conversion",
    supportsQuality: true,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: false,
    defaultQuality: 85,
  },
  "jpg-to-webp": {
    label: "JPG → WebP",
    description: "Convert JPEG images to WebP format.",
    actionLabel: "Convert JPG to WebP",
    apiEndpoint: "/image/jpg-to-webp",
    acceptedFormats: ".jpg,.jpeg",
    category: "Image Conversion",
    supportsQuality: true,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: false,
    defaultQuality: 80,
  },
  "image-resize": {
    label: "Image Resize",
    description: "Resize images while preserving quality.",
    actionLabel: "Resize Image",
    apiEndpoint: "/image/resize",
    acceptedFormats: ".jpg,.jpeg,.png,.webp",
    category: "Image Optimization",
    supportsQuality: false,
    supportsResize: true,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: false,
  },
  "image-compress": {
    label: "Image Compress",
    description: "Compress images to reduce file size.",
    actionLabel: "Compress Image",
    apiEndpoint: "/image/compress",
    acceptedFormats: ".jpg,.jpeg,.png,.webp",
    category: "Image Optimization",
    supportsQuality: true,
    supportsResize: false,
    supportsMaxSize: true,
    supportsPages: false,
    supportsMultiple: false,
    defaultQuality: 75,
  },
  "images-to-pdf": {
    label: "Images → PDF",
    description: "Convert multiple images into a single PDF.",
    actionLabel: "Build PDF",
    apiEndpoint: "/pdf/images-to-pdf",
    acceptedFormats: ".jpg,.jpeg,.png,.webp",
    category: "PDF Tools",
    supportsQuality: false,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: true,
  },
  "pdf-merge": {
    label: "PDF Merge",
    description: "Merge multiple PDF files into one document.",
    actionLabel: "Merge PDFs",
    apiEndpoint: "/pdf/merge",
    acceptedFormats: ".pdf",
    category: "PDF Tools",
    supportsQuality: false,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: true,
  },
  "pdf-split": {
    label: "PDF Split",
    description: "Split a PDF into smaller documents.",
    actionLabel: "Split PDF",
    apiEndpoint: "/pdf/split",
    acceptedFormats: ".pdf",
    category: "PDF Tools",
    supportsQuality: false,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: true,
    supportsMultiple: false,
  },
  "zip-extractor": {
    label: "ZIP Extractor",
    description: "Extract files securely from ZIP archives.",
    actionLabel: "Extract ZIP",
    apiEndpoint: "/zip/extract",
    acceptedFormats: ".zip",
    category: "Archive Tools",
    supportsQuality: false,
    supportsResize: false,
    supportsMaxSize: false,
    supportsPages: false,
    supportsMultiple: false,
  },
};
